version: '2'

services:
  powerbi-php-sample:
    image: powerbi-php-sample:debug
    build:
      dockerfile: Dockerfile.debug
    ports:
      - "8080:80"
    env_file: 
      - secrets.env
    volumes:
      - ./src/website/wwwroot:/var/www/html